name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.6.2
        run_install: true
    - name: Check
      run: |
        pnpm typeck
        pnpm fmt:check
    - name: Test
      run: pnpm test
