name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install
      run: yarn
    - name: Check
      run: |
        yarn typeck
        yarn fmt:check
    - name: Test
      run: yarn test
